### PR TITLE
add: multithreading, --api flag to get information about GitHub API limits, simple progressbar, new script and 5-characters_AAAAA-ZZZZZ.txt

### PR DESCRIPTION
**Pull request by yyxa**
add:
multithreading for original script

--api flag to get information about requests to GitHub API

simple progress bar: checked/sum of file lines

5-characters_AAAAA-ZZZZZ.txt

new script:
original one was 5k requests per hour and it cant check usernames that github does not give to anyone

new one is 6k(100 per minute * 60 = 6000) requests per hour, it checks the possibility of changing the username using cookies and a session token

update:
README.md

### CODE REVIEW

**Comment by oood** [comment]
This is a breaking change, and I'm glad to see it. Would you like to help improve the readme? I'm sure the same breaking changes are needed there too.

**Comment by yyxa** [comment]
ok, I'll improve the readme, but I need to make a couple of fixes, because the scripts don't work on mac os

**Comment by yyxa** [comment]
Check new README.md

**Comment by oood** [comment]
> Check new README.md

Sorry for the late reply, thanks for your contribution, it has been merged. 

And you are invited to join this repository (granting you read-write access to this repository). 

Thanks for your contribution.

**Pull request merged**
